language: java
jdk:
- oraclejdk8
script: mvn -B verify
deploy:
  api_key:
    secure: HbF8N92OYm1Qe40ZzJrHoujblIbx7LIAzd1MlSS4CV6SPEVEtHJ0ee6u/zOUeJBBgvE4/6tiuq0bFu4pcBamYofgRoFmpVB5vwOVl/bqeFx/3vohkpgs0IVSlvGCH/bUW/yCwP58zt1UhzLztMigKwRJFj0vczDcBOLaNdVdeXRFTutnBcPcEUHt5umP4i4tNpm7HLv7gQrg5Xc524k98WKdz+RiTSUDVpFRfCYvFZ06hB8DDQgvsTCmvtXdpHDjvj38z2iU0xN0xyCziYrWGCZHvot5nnKCxm2j5snKSEnWS5iLOZh72tfyFQ3jiDBWXOiz+kQgX5/3OzZ1XdFWxM3l2w0JtG6fgtFaLkz2OSr8jRf9jjKXAD0/NeeFlpy3JtT0wJbN7ozeAFLn5n7wYikhLVhGvcwXlQeRR0OEUMRfifvebRg3kAOlUsTE6iZf8cZC8ZiVkq3i7wdRb4ZGdYGmAZE6wNHSsWb79I697jMKusUM3e6+1RPJvYFNPGlylFeqH4EsL3DaXfa7d1nA6XWmOR6z0rH7Y7uLc/ePDNTX90ZE88RxvWnx6XZnpNCbcqwOhLh8Kcv9jaE1Cao7BMeQDkKRm0lGNLDNU2Nu08Yqks8T+D+x1DiIGiy8CqrsibYZLGOn9/fma/cm63xw3Y1DVeS6eeOb+bufHOszqrk=
