rJavaServer:
  rengine:
    blockFunction: source("/Users/jfcorugedo/Documents/git/kmd/kmd-math/blockFunction.R")
    rserveConf: /Users/jfcorugedo/Documents/git/RJavaServer/rserve_local.conf
    rexe: /Library/Frameworks/R.framework/Versions/3.2/Resources/bin/exec/R
    enableJRI: false
  metrics:
    enabled: false
    period: 10